### PR TITLE
gh-73: Add the main script to pyproject.toml

### PR DESCRIPTION
**Pull request by qexat**
Closes issue #73

Typing the following line now directly runs the bot:

```
poetry run bot
```

For technical reasons, I had to move `mcodingbot/__main__.py` main code to a function, and I believe it's better as it is in this commit.

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
I think it should be `poetry run bot` (imo using the name of the bot in the code is a terrible mistake)

**Comment by qexat** [comment]
Do I really have to type a function that takes no args and returns nothing...

**Comment by qexat** [comment]
> I think it should be `poetry run bot` (imo using the name of the bot in the code is a terrible mistake)

I just copy-pasted, I understand your statement and will apply as I fix this stupid typechecking issue

**Comment by qexat** [comment]
`mypy` still fails typechecking when I run it when `nox` locally

**Comment by qexat** [comment]
@Lunarmagpie it passes the checks now

**Review by Lunarmagpie — APPROVED** [review]

**Comment by qexat** [comment]
@MithicSpirit @CircuitSacul @Endercheif

**Comment by MithicSpirit** [comment]
lgtm

**Review by CircuitSacul — APPROVED** [review]

**Comment by qexat** [comment]
so we are waiting for endercheif?

**Review by trag1c — APPROVED** [review]

**Pull request merged**
