### PR TITLE
feat: RUST_REGEX supports more messages

### PR DESCRIPTION
**Pull request by qexat**
:rocket: :fire: :stars:

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
This is amazing. I think it should also match "blazing fast".

**Review by qexat — COMMENTED** [review]
rust

**Comment by qexat** [comment]
rust may be fast but PR reviews are slow as hell :trollface: deleting that branch sorry folks

**Comment by CircuitSacul** [comment]
oof sorry, I've been super busy and I completely forgot. Also, I don't think I'm the only one with write access to the bot.

**Pull request closed without merging**
