### PR TITLE
Added reaction and link

### PR DESCRIPTION
**Pull request by soupless**
Added 💀 react for messages having the word "forgor" and a 💀
and included https://mcoding.io in the `links` command.

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
The link changes and forgor message shouldn't be done in the same PR. May seem pedantic but I want to keep different purposes for PRs separated.

**Comment by soupless** [comment]
Are changes supposed (or recommended) to be in different PRs, instead of one? I thought changes should be bundled as much as possible.

**Comment by Lunarmagpie** [comment]
One PR should do one task. Otherwise, maintainers have a harder time reviewing and the larger amount to review can lead to longer reviews. Also for a repository that squashes commits it leads to a easier to read commit history.

**Comment by trag1c** [comment]
Closing this due to inactivity

**Pull request closed without merging**
